   Vagrant.configure("2") do |config|
     config.vm.define "server" do |server|
       server.vm.box = "ubuntu/bionic64"
       server.vm.network "private_network", type: "dhcp"
       server.vm.hostname = "server"
       server.vm.provision "shell", path: "provision_server.sh"
     end

     config.vm.define "client" do |client|
       client.vm.box = "ubuntu/bionic64"
       client.vm.network "private_network", type: "dhcp"
       client.vm.hostname = "client"
       client.vm.provision "shell", path: "provision_client.sh"
     end
   end
   
